<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hexa</string>
	</array>
	<key>scopeName</key>
	<string>source.hexa</string>
	<key>uuid</key>
	<string>66b008f2-f9ad-481c-8d85-ecf5d0d88ff9</string>
	<key>name</key>
	<string>Hexa</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>invalid.hexa</string>
			<key>match</key>
			<string>;</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.others.hexa</string>
			<key>match</key>
			<string>\s*#(if|else|end|error|elseif)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.declaration.hexa</string>
			<key>match</key>
			<string>\b(declare|extends|implements)\b</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enum</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.type.hexa</string>
			<key>match</key>
			<string>\b(class|interface|enum|let|var|fun)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.modifier.hexa</string>
			<key>match</key>
			<string>\b(import|private|static)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.statement.hexa</string>
			<key>match</key>
			<string>\b(try|catch|break|case|continue|do|else|if|in|for|return|throw|switch|while)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.type.hexa</string>
			<key>match</key>
			<string>\b([A-Z][A-Za-z_0-9]*)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.expressions-and-types.hexa</string>
			<key>match</key>
			<string>\b(as|is|new|this|super|and|or|not)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.hexa</string>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>storage.attribute.hexa</string>
			<key>match</key>
			<string>@[a-z_][a-zA-Z_0-9]*\b</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>unsafe operators, same color as null</string>
			<key>name</key>
			<string>constant.language.hexa</string>
			<key>match</key>
			<string>.assumeNotNull\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.operator.range.hexa</string>
			<key>match</key>
			<string>\.\.\.</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>.a.b</string>
			<key>match</key>
			<string>(\.)([a-z_][a-zA-Z_0-9]*)((\.)([a-z_][a-zA-Z_0-9]*))?</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.access.dot.hexa</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.hexa</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.access.dot.hexa</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.type.variable.hexa</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.hexa</string>
			<key>begin</key>
			<string>\$[a-z_][a-zA-Z_0-9]*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.language.hexa</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>constant.language.hexa</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#macro-nested</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.hexa</string>
			<key>match</key>
			<string>\$[a-z_][a-zA-Z_0-9]*\b</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literal</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>macro-nested</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.declaration.hexa</string>
					<key>match</key>
					<string>\$[a-z_][a-zA-Z_0-9]*\b</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.language.hexa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.language.hexa</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#macro-nested</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>doc-comment-markup</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.attribute.hexa</string>
					<key>match</key>
					<string>@[a-z_][a-zA-Z_0-9]*\b</string>
				</dict>
			</array>
		</dict>
		<key>comment-markup</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.declaration.hexa</string>
					<key>match</key>
					<string>\b(TODO|NOTE)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.hexa</string>
					<key>match</key>
					<string>http(s)?://[a-zA-Z./[0-9]-?&amp;✓%=+#@_]+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.hexa</string>
					<key>begin</key>
					<string>```</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.language.hexa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>```</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.language.hexa</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>comment.block.hexa</string>
							<key>match</key>
							<string>^[ ]*// </string>
						</dict>
						<dict>
							<key>name</key>
							<string>comment.block.hexa</string>
							<key>match</key>
							<string>^[ ]*/// </string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.hexa</string>
					<key>begin</key>
					<string>`</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.language.hexa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>`|$</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.language.hexa</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.bold.markdown</string>
					<key>begin</key>
					<string>\*\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bold.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*\*|$</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bold.markdown</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>markup.italic.markdown</string>
							<key>begin</key>
							<string>\*</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.italic.markdown</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\*</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.italic.markdown</string>
								</dict>
							</dict>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>markup.italic.markdown</string>
					<key>begin</key>
					<string>\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*|$</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.markdown</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.block.hexa</string>
					<key>begin</key>
					<string>/\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.hexa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.hexa</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment-markup</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^\s+)?(?=//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.hexa</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=$)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>comment.block.documentation.hexa</string>
							<key>begin</key>
							<string>(?&lt;!/)(///)(?!/)</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.hexa</string>
								</dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>constant.character.escape.hexa</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#doc-comment-markup</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#comment-markup</string>
								</dict>
							</array>
							<key>end</key>
							<string>(?=$)</string>
						</dict>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.hexa</string>
							<key>begin</key>
							<string>(?&lt;!/)//(?:(?!/)|(?=//))</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.hexa</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#comment-markup</string>
								</dict>
							</array>
							<key>end</key>
							<string>(?=$)</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>escaped-char</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.hexa</string>
					<key>match</key>
					<string>\\[0\\tnr"']</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.hexa</string>
					<key>match</key>
					<string>\\(x\h{2}|u\h{4}|U\h{8})</string>
				</dict>
				<dict>
					<key>name</key>
					<string>invalid.illegal.constant.character.escape.hexa</string>
					<key>match</key>
					<string>\\[^uxU]</string>
				</dict>
			</array>
		</dict>
		<key>literal</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#literal-float</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal-number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal-big-number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal-hexadecimal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal-big-hexadecimal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal-binary</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal-big-binary</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literal-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw-string</string>
				</dict>
			</array>
		</dict>
		<key>literal-big-number</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.hexa</string>
			<key>match</key>
			<string>\b([0-9]+n)\b</string>
		</dict>
		<key>literal-number</key>
		<dict>
			<key>comment</key>
			<string>1_2_3u64</string>
			<key>name</key>
			<string>constant.numeric.hexa</string>
			<key>match</key>
			<string>\b([0-9][0-9_]*([iu](8|16|32|64))?)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.hexa</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.numeric.hexa</string>
				</dict>
			</dict>
		</dict>
		<key>literal-big-hexadecimal</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.hexa</string>
			<key>match</key>
			<string>\b(0x[0-9A-Fa-f]+n)\b</string>
		</dict>
		<key>literal-hexadecimal</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.hexa</string>
			<key>match</key>
			<string>\b((0x)[0-9A-Fa-f]+([iu](8|16|32|64))?)\b</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.numeric.hexa</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.numeric.hexa</string>
				</dict>
			</dict>
		</dict>
		<key>literal-big-binary</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.hexa</string>
			<key>match</key>
			<string>\b(0b[0-1]+n)\b</string>
		</dict>
		<key>literal-binary</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.hexa</string>
			<key>match</key>
			<string>\b(0b[0-1]+([iu](8|16|32|64))?)\b</string>
		</dict>
		<key>literal-float</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.hexa</string>
			<key>match</key>
			<string>\b((([1-9][0-9]*)|(0[1-9][0-9]+)|0)\.[0-9]+(f(16|32))?)\b</string>
		</dict>
		<key>literal-string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(["])</string>
					<key>end</key>
					<string>(["])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.hexa</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.hexa</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.hexa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quoted-text</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(['])</string>
					<key>end</key>
					<string>(['])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.hexa</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.hexa</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.hexa</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quoted-text</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>raw-string</key>
		<dict>
			<key>name</key>
			<string>string.quoted.hexa</string>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.hexa</string>
				</dict>
			</dict>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.hexa</string>
				</dict>
			</dict>
		</dict>
		<key>enum</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>.Tag</string>
					<key>match</key>
					<string>(\.)([A-Z][A-Za-z0-9_]*)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.access.dot.hexa</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.enum.hexa</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>comment</key>
					<string>enum A B {</string>
					<key>match</key>
					<string>\b(enum)\s+([A-Z][A-Za-z0-9_]*)\s+([A-Z][A-Za-z0-9_]*)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.type.enum.hexa</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.type.hexa</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.enum.hexa</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#operator-character</string>
				</dict>
			</array>
		</dict>
		<key>operator-character</key>
		<dict>
			<key>name</key>
			<string>keyword.operator.hexa</string>
			<key>match</key>
			<string>[\\\/=\-+!*%&lt;&gt;&amp;|^~,\?:\[\]]</string>
		</dict>
		<key>quoted-text</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>meta.embedded.line.hexa</string>
					<key>contentName</key>
					<string>source.hexa</string>
					<key>begin</key>
					<string>\\\(</string>
					<key>end</key>
					<string>\)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.hexa</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.hexa</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#escaped-char</string>
				</dict>
			</array>
		</dict>
		<key>whitespace</key>
		<dict>
			<key>match</key>
			<string>TODO_whitespace</string>
		</dict>
	</dict>
</dict>
</plist>
